save_dir:
  cryptodownload: "data/external/cryptodownload"
  coinmarketcap: "data/external/coinmarketcap"
cryptodownload:
  json_urls:
    binance: "https://api.cryptodatadownload.com/v1/data/ohlc/binance/guest/spot/available?_=1740047643800&format=json"
    gemini: "https://api.cryptodatadownload.com/v1/data/ohlc/gemini/guest/available?_=1740057730875&format=json"
    bitstamp: "https://api.cryptodatadownload.com/v1/data/ohlc/bitstamp/guest/spot/available?_=1740058272110&format=json"
coinmarketcap:
  maps:
    cryptocurrency_map: "https://pro-api.coinmarketcap.com/v1/cryptocurrency/map"
    fiat_map:  "https://pro-api.coinmarketcap.com/v1/fiat/map"
    exchange_map: "https://pro-api.coinmarketcap.com/v1/exchange/map"
trading_pairs:
  -
    base_name: "Bitcoin"
    quote_name: "United States Dollar"
    timeframe: "minute"
    from_year: 2020
  -
    base_name: "Bitcoin"
    quote_name: "Tether USDt"
    timeframe: "minute"
    from_year: 2020