name: E3 ML Continuous Delivery (Tests Only)

on:
  push:
    paths:
      - 'E3-ml/**'
      - '.github/workflows/e3-ml-cd.yml'
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: E3-ml
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: E3-ml/requirements.txt

      - name: Install system libs
        run: |
          sudo apt-get update
          sudo apt-get install -y libgomp1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-cov

      - name: Run tests
        env:
          PYTHONPATH: ./src
        run: |
          pytest -q --maxfail=1 --disable-warnings

      - name: Generate coverage
        if: always()
        env:
          PYTHONPATH: ./src
        run: |
          pytest --cov=src --cov-report=xml:coverage.xml || true

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e3-ml-coverage
          path: E3-ml/coverage.xml
