name: E4 App Tests

on:
  push:
    paths:
      - 'E4-app/**'
      - '.github/workflows/tests.yml'
  pull_request:
    paths:
      - 'E4-app/**'

jobs:
  tests:
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.11', '3.12']
    defaults:
      run:
        working-directory: E4-app
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: E4-app/requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-cov

      - name: Run tests (fast)
        env:
          SECRET_KEY: ci-test-secret
          URL_E1: http://fake-e1
          URL_E3: http://fake-e3
          E3_API_USERNAME: test
          E3_API_PASSWORD: test
        run: |
          pytest -q --maxfail=1 --disable-warnings

      - name: Coverage report
        if: always()
        env:
          SECRET_KEY: ci-test-secret
          URL_E1: http://fake-e1
          URL_E3: http://fake-e3
          E3_API_USERNAME: test
          E3_API_PASSWORD: test
        run: |
          pytest --cov=. --cov-report=xml --cov-report=term-missing || true

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.os }}-${{ matrix.python-version }}
          path: E4-app/coverage.xml
